import React, { useContext, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import DeviceTable from '../../components/DeviceTable';
import DeviceMap from '../../components/DeviceMap';
import AppContext from '../../context/app';

// Hardcoded data. Would come from the database and WebSocket, as with the dashboard
const data = {
  devices: [
    {
      carbon_monoxide: 10.0,
      firefighter_code: 'Graf 7',
      firefighter_email: 'graf0007@graf.cat',
      firefighter_first: 'Bombero',
      device_id: 7,
      firefighter_last: 'Graf 7',
      humidity: 46,
      nitrogen_dioxide: 0.55,
      temperature: 41,
      latitude: '41.364031',
      longitude: '1.831706',
      timestamp_mins: 'Tue, 11 Feb 2020 10:58:00 GMT',
      id: 7,
      device_version: 1,
      lastCheckin: 'Tue, 11 Feb 2020 10:58:00 GMT',
      isUserOwner: true,
    },
    {
      carbon_monoxide: 10.0,
      firefighter_code: 'Graf 3',
      firefighter_email: 'graf0003@graf.cat',
      firefighter_first: 'Bombero',
      device_id: 3,
      firefighter_last: 'Graf 3',
      humidity: 67,
      nitrogen_dioxide: 0.5,
      temperature: 33,
      latitude: '40.486027649186646',
      longitude: '0.2514942041995945',
      timestamp_mins: 'Tue, 11 Feb 2020 10:56:00 GMT',
      id: 3,
      device_version: 1,
      lastCheckin: 'Tue, 11 Feb 2020 10:58:00 GMT',
      isUserOwner: true,
    },
    {
      carbon_monoxide: 10.0,
      firefighter_code: 'Graf 3',
      firefighter_email: 'graf0003@graf.cat',
      firefighter_first: 'Bombero',
      device_id: 5,
      firefighter_last: 'Graf 3',
      humidity: 67,
      nitrogen_dioxide: 0.5,
      temperature: 33,
      latitude: '39.552386966400555',
      longitude: '-0.41370484730314183',
      timestamp_mins: 'Tue, 11 Feb 2020 10:56:00 GMT',
      id: 5,
      device_version: 1,
      lastCheckin: 'Tue, 11 Feb 2020 10:58:00 GMT',
      isUserOwner: true,
    },
  ],
};

const processDeviceData = (devices) => {
  return devices.slice().map((s) => ({
    ...s,
    statusColor: (() => {
      if (!s.lastCheckin) {
        return 'yellow';
      }

      const secondsAgo =
        Math.floor(Date.now() / 1000) -
        Math.floor(new Date(s.lastCheckin) / 1000);

      if (secondsAgo > 604800) {
        return 'yellow';
      }

      return 'green';
    })(),
  }));
};

const MapPage = (props) => {
  const { t, currentUser, setCurrentUser, addToast } = useContext(AppContext);

  const navigate = useNavigate();

  const active = props.active;
  const language = props.language;
  // const page = props.page;
  const setActive = props.setActive;
  // const setPage = props.setPage;

  /*
  const [execQuery, { data, loading }] = useLazyQuery(GET_DEVICES, {
    errorPolicy: 'all',
    // TODO
    onError() {
      addToast({
        kind: 'warning',
        caption:
          'There were errors generated by the device query that may affect the display of relevant data. If this is a recurring warning, consider opening an issue.',
        title: 'Device Data Loaded with Error(s)',
      })
    },
  })
  */

  const [loading, setLoading] = useState('Loading...');

  const [pageSize, setPageSize] = useState(5);
  const [page, setPage] = useState(1);
  const [devices, setDevices] = useState([]);
  const [currentlyVisibleDevice, setCurrentlyVisibleDevice] = useState([]);

  const [shouldShowSideMenu, setShouldShowSideMenu] = useState(false);
  const [displayedDevice, setDisplayedDevice] = useState({});
  const [currentHoveredDevice, setCurrentHoveredDevice] = useState();

  /*
  useEffect(() => {
    execQuery()
  }, [execQuery])
  */

  useEffect(() => {
    if (data && data.devices) {
      setDevices(processDeviceData(data.devices));
    }
  }, [data]);

  useEffect(() => {
    setCurrentlyVisibleDevice(
      devices.slice((page - 1) * pageSize, page * pageSize)
    );
  }, [page, pageSize, devices]);

  const onPaginationChange = (paginationInfo) => {
    setPage(paginationInfo.page);
    setPageSize(paginationInfo.pageSize);
  };

  const onDeviceHover = (index) => {
    setCurrentHoveredDevice(index);
  };

  return (
    <div className="bx--grid bx--grid--full-width map-content">
      <div className="bx--row">
        <div className="bx--col-md-16">
          <h1 className="map-page__heading">{t('content.map.heading')}</h1>
        </div>
      </div>

      <div className="bx--row">
        <div className="bx--col-md-16">
          <h2 className="map-page__subheading">
            {t('content.map.subheading')}
          </h2>
        </div>
      </div>

      <div className="device-map__container">
        <DeviceMap
          devices={devices}
          setDisplayedDevice={setDisplayedDevice}
          setShouldShowSideMenu={setShouldShowSideMenu}
          onDeviceHover={onDeviceHover}
          currentHoveredDevice={currentHoveredDevice}
        />
      </div>

      <div className="device-table__container">
        <DeviceTable
          loading={loading}
          navigate={navigate}
          devices={devices}
          setDevices={setDevices}
          page={page}
          pageSize={pageSize}
          onPaginationChange={onPaginationChange}
          currentlyVisibleDevice={currentlyVisibleDevice}
          shouldShowSideMenu={shouldShowSideMenu}
          setShouldShowSideMenu={setShouldShowSideMenu}
          displayedDevice={displayedDevice}
          setDisplayedDevice={setDisplayedDevice}
          onDeviceHover={onDeviceHover}
          currentHoveredDevice={currentHoveredDevice}
        />
      </div>
    </div>
  );
};

export default MapPage;
