FROM node:16-alpine

WORKDIR /app
COPY package.json .

#for node-gyp    
RUN apk add --no-cache python3 make g++

RUN yarn install
# RUN npm install react-scripts -g --silent
#TODO: optimize COPY here. It copies node_modules over to the image again
COPY . .

CMD ["yarn", "start-ui"]